/* Plain-language privacy copy. Detailed identifiers stay out of visitor-facing text. */
(() => {
  "use strict";

  const updates = {
    lv: {
      policyDataTitle: "Kādus datus apstrādājam",
      policyDataText: "Kad sazināties ar mums vai piesakāt vizīti, varat norādīt savu vārdu, tālruņa numuru, e-pasta adresi (ja izvēlaties to norādīt), vēlamo datumu, interesējošo pakalpojumu un komentāru. Vietnē fotogrāfijas netiek augšupielādētas — tās varat pievienot tieši WhatsApp sarakstē. Ja esat piekrituši vietnes analītikai, Google Analytics var apstrādāt arī informāciju par apmeklētajām lapām un darbībām vietnē, sesijas datus, aptuvenu atrašanās vietu, ierīces tipu un modeli, operētājsistēmu, pārlūkprogrammu, valodu un ekrāna parametrus. Ja pieteikumā norādāt e-pasta adresi, Google Analytics var saņemt arī Jūsu norādīto e-pasta adresi un tālruņa numuru kā lietotāja sniegtus datus; Google tags šos datus normalizē un aizsargā ar SHA-256 vienvirziena jaukšanu pirms to izmantošanas atbilstības noteikšanai.",
      policyPurposeTitle: "Kāpēc šie dati ir vajadzīgi",
      policyPurposeText: "Kontaktinformāciju izmantojam, lai sagatavotu Jūsu pieteikumu WhatsApp, atbildētu uz jautājumu, vienotos par vizīti un nodrošinātu saskaņoto pakalpojumu. Ar Jūsu piekrišanu Google Analytics izmantojam vietnes apmeklējuma un konversiju mērīšanai, auditoriju un lietošanas paradumu analīzei, kā arī vietnes uzlabošanai. Google signals var sasaistīt CATRIN vietnes analītikas datus ar Google kontā pierakstītu lietotāju informāciju, ja attiecīgais lietotājs savā Google kontā ir atļāvis šādu izmantošanu; tas var nodrošināt starpierīču, demogrāfijas un interešu pārskatus. Ar piekrišanu analītikas dati un lietotāja sniegtie dati var tikt izmantoti arī uzlabotai konversiju mērīšanai, auditoriju atbilstības noteikšanai, remarketingam un personalizētai reklāmai saistītajos Google pakalpojumos.",
      policyStorageTitle: "Datu glabāšana un nodošana",
      policyStorageText: "CATRIN vietne pieteikuma laukos ievadītos datus savā serverī vai datubāzē neglabā — pēc nosūtīšanas tiek atvērts WhatsApp ar sagatavotu ziņu. Jūsu analītikas izvēle tiek saglabāta pārlūkprogrammas lokālajā krātuvē. Pēc piekrišanas Google Analytics var iestatīt pirmās puses sīkdatnes, tostarp _ga un _ga_*, kuru glabāšanas termiņš pēc noklusējuma var būt līdz diviem gadiem. Google Analytics un ar to saistītos Google pakalpojumus nodrošina Google; šo pakalpojumu ietvaros dati var tikt apstrādāti ārpus Latvijas un Eiropas Ekonomikas zonas saskaņā ar Google piemērotajiem datu aizsardzības mehānismiem un noteikumiem. Sazinoties ar mums WhatsApp, Instagram vai Facebook, piemērojami arī šo pakalpojumu sniedzēju noteikumi.",
      policyExternalTitle: "Karte un ārējās saites",
      policyExternalText: "Kontaktu lapā pieejama Google karte, bet saites uz Google Maps, Waze, WhatsApp, Instagram un Facebook atveras attiecīgo pakalpojumu vidē. Atverot iegulto karti vai ārēju pakalpojumu, attiecīgais pakalpojuma sniedzējs var saņemt tehnisku informāciju par Jūsu ierīci un savienojumu. Uz šiem pakalpojumiem attiecas to pašu privātuma noteikumi.",
      policyCookiesTitle: "Sīkdatnes, Google Analytics un reklāmas funkcijas",
      policyCookiesText: "Google Analytics un ar to saistītās reklāmas funkcijas tiek aktivizētas tikai pēc Jūsu piekrišanas. Izvēloties “Pieņemt”, Jūs atļaujat izmantot šīs funkcijas saskaņā ar iepriekš aprakstītajiem nolūkiem. Izvēloties “Nē, paldies”, tās netiek aktivizētas. Savu izvēli jebkurā laikā varat mainīt vietnes kājenē, izvēloties “Sīkdatņu iestatījumi”.",
      policyUpdated: "Atjaunots: 2026. gada 19. augustā.",
    },
    ru: {
      policyDataTitle: "Какие данные мы обрабатываем",
      policyDataText: "Когда Вы связываетесь с нами или записываетесь на визит, Вы можете указать имя, номер телефона, адрес электронной почты (если решите его указать), желаемую дату, интересующую услугу и комментарий. Фотографии не загружаются на сайт — их можно прикрепить прямо в чате WhatsApp. Если Вы согласились на аналитику сайта, Google Analytics также может обрабатывать сведения о просмотренных страницах и действиях на сайте, данные сеанса, приблизительное местоположение, тип и модель устройства, операционную систему, браузер, язык и параметры экрана. Если в заявке указан e-mail, Google Analytics также может получить указанные Вами e-mail и номер телефона как данные, предоставленные пользователем; Google tag нормализует эти данные и защищает их односторонним хешированием SHA-256 до использования для сопоставления.",
      policyPurposeTitle: "Для чего нужны эти данные",
      policyPurposeText: "Контактные данные используются для подготовки Вашей заявки в WhatsApp, ответа на вопрос, согласования визита и оказания согласованной услуги. С Вашего согласия Google Analytics используется для измерения посещений и конверсий, анализа аудиторий и поведения на сайте и улучшения сайта. Google signals может связывать аналитические данные CATRIN с информацией пользователей, вошедших в аккаунт Google, если соответствующий пользователь разрешил такое использование в настройках своего аккаунта; это может использоваться для межустройственных, демографических отчётов и отчётов по интересам. При наличии согласия аналитические и предоставленные пользователем данные также могут использоваться для улучшенного измерения конверсий, сопоставления аудиторий, ремаркетинга и персонализированной рекламы в связанных сервисах Google.",
      policyStorageTitle: "Хранение и передача данных",
      policyStorageText: "Сайт CATRIN не сохраняет данные из полей заявки на собственном сервере или в базе данных — после отправки открывается WhatsApp с подготовленным сообщением. Ваш выбор по аналитике сохраняется в локальном хранилище браузера. После согласия Google Analytics может устанавливать собственные cookie, включая _ga и _ga_*, срок хранения которых по умолчанию может составлять до двух лет. Google Analytics и связанные сервисы Google предоставляются компанией Google; в рамках этих сервисов данные могут обрабатываться за пределами Латвии и Европейской экономической зоны с применением предусмотренных Google механизмов защиты данных и условий. При общении через WhatsApp, Instagram или Facebook также действуют правила соответствующих сервисов.",
      policyExternalTitle: "Карта и внешние ссылки",
      policyExternalText: "На странице контактов доступна карта Google, а ссылки на Google Maps, Waze, WhatsApp, Instagram и Facebook открываются в соответствующих сервисах. При загрузке встроенной карты или переходе во внешний сервис его поставщик может получить технические сведения об устройстве и соединении. Для этих сервисов действуют их собственные правила конфиденциальности.",
      policyCookiesTitle: "Cookie, Google Analytics и рекламные функции",
      policyCookiesText: "Google Analytics и связанные с ним рекламные функции активируются только после Вашего согласия. Выбирая «Принять», Вы разрешаете использование этих функций для целей, описанных выше. Если Вы выбираете «Нет, спасибо», они не активируются. Свой выбор можно изменить в любое время через «Настройки cookie» в нижней части сайта.",
      policyUpdated: "Последнее обновление: 19 августа 2026 года.",
    },
    en: {
      policyDataTitle: "Data we process",
      policyDataText: "When you contact us or request a visit, you may provide your name, phone number, email address (if you choose to provide it), preferred date, requested service and a note. Photographs are not uploaded to the website — you can attach them directly in a WhatsApp chat. If you consent to website analytics, Google Analytics may also process information about pages viewed and actions on the website, session data, approximate location, device type and model, operating system, browser, language and screen parameters. If you provide an email address in the booking form, Google Analytics may also receive the email address and phone number you supplied as user-provided data; the Google tag normalizes this data and protects it with one-way SHA-256 hashing before it is used for matching.",
      policyPurposeTitle: "Why we use this data",
      policyPurposeText: "We use contact details to prepare your WhatsApp request, answer your question, arrange a visit and provide the agreed service. With your consent, Google Analytics is used to measure visits and conversions, analyse audiences and website usage, and improve the website. Google signals may associate CATRIN Analytics data with information from users signed in to Google where the relevant user has enabled such use in their Google account; this may provide cross-device, demographic and interest reporting. With consent, Analytics data and user-provided data may also be used for enhanced conversion measurement, audience matching, remarketing and personalised advertising in connected Google services.",
      policyStorageTitle: "Storage and sharing",
      policyStorageText: "The CATRIN website does not store the information entered in the booking fields on its own server or database — submitting the form opens WhatsApp with a prepared message. Your analytics choice is stored in the browser's local storage. After consent, Google Analytics may set first-party cookies including _ga and _ga_*, whose default lifetime may be up to two years. Google Analytics and related Google services are provided by Google; within those services data may be processed outside Latvia and the European Economic Area under the data-protection mechanisms and terms applied by Google. When you contact us through WhatsApp, Instagram or Facebook, those services' own terms also apply.",
      policyExternalTitle: "Map and external links",
      policyExternalText: "The contact page includes a Google map, while links to Google Maps, Waze, WhatsApp, Instagram and Facebook open in the relevant external services. When an embedded map or external service is opened, that provider may receive technical information about your device and connection. Each service's own privacy terms apply.",
      policyCookiesTitle: "Cookies, Google Analytics and advertising features",
      policyCookiesText: "Google Analytics and related advertising features are activated only after you give your consent. By choosing “Accept”, you allow these features to be used for the purposes described above. If you choose “No, thank you”, they are not activated. You can change your choice at any time through “Cookie settings” in the site footer.",
      policyUpdated: "Last updated: 19 August 2026.",
    },
  };

  const language = document.documentElement.lang?.toLowerCase().split("-")[0] || "lv";
  Object.assign(window.CATRIN_COPY?.[language] || {}, updates[language] || updates.lv);
})();
